export const DispatchConst = {
  ADD_POST: 'ADD_POST',
  ADD_MESSAGE: 'ADD_MESSAGE',
  NEW_MESSAGE_TEXT: 'NEW_MESSAGE_TEXT',
  SET_LIKE_COUNT: 'SET_LIKE_COUNT',
  SET_FOLLOW_USER: 'SET_FOLLOW_USER',
  SET_USERS: 'SET_USERS',
  SET_PAGINATION: 'SET_PAGINATION',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_FETCHING: 'SET_FETCHING',
  SET_PROFILE: 'SET_PROFILE',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_FOLLOWING_PROGRESS: 'SET_FOLLOWING_PROGRESS',
}
